export const brandAliases: ReadonlyArray<readonly [alias: string, canonical: string]> = [
  ['Maison Francis Kurkdjian', 'Maison Francis Kurkdjian'],
  ['Jean Paul Gaultier', 'Jean Paul Gaultier'],
  ['Initio Parfums Privés', 'Initio Parfums Privés'],
  ['Initio Parfums Prives', 'Initio Parfums Privés'],
  ['Liquides Imaginaires', 'Liquides Imaginaires'],
  ['Marc-Antoine Barrois', 'Marc-Antoine Barrois'],
  ['Marc Antoine Barrois', 'Marc-Antoine Barrois'],
  ['Vilhelm Parfumerie', 'Vilhelm Parfumerie'],
  ['Lorenzo Pazzaglia', 'Lorenzo Pazzaglia'],
  ['Parfums de Marly', 'Parfums de Marly'],
  ['Frederic Malle', 'Frederic Malle'],
  ['Maison Crivelli', 'Maison Crivelli'],
  ['Clive Christian', 'Clive Christian'],
  ['Attar Collection', 'Attar Collection'],
  ['Tiziana Terenzi', 'Tiziana Terenzi'],
  ['Louis Vuitton', 'Louis Vuitton'],
  ['Penhaligon’s', 'Penhaligon’s'],
  ["Penhaligon's", 'Penhaligon’s'],
  ['Memo Paris', 'Memo Paris'],
  ['Tom Ford', 'Tom Ford'],
  ['Le Labo', 'Le Labo'],
  ['Ex Nihilo', 'Ex Nihilo'],
  ['Amouage', 'Amouage'],
  ['Byredo', 'Byredo'],
  ['Chanel', 'Chanel'],
  ['Creed', 'Creed'],
  ['Dior', 'Dior'],
  ['HFC', 'HFC'],
  ['Kilian Paris', 'Kilian'],
  ['By Kilian', 'Kilian'],
  ['Kilian', 'Kilian'],
  ['Mancera', 'Mancera'],
  ['Montale', 'Montale'],
  ['Nishane', 'Nishane'],
  ['Sospiro', 'Sospiro'],
  ['Versace', 'Versace'],
  ['Xerjoff', 'Xerjoff'],
].sort((a, b) => b[0].length - a[0].length);

