const aliases = [
  ['Les Liquides Imaginaires', 'Liquides Imaginaires'],
  ['Juliette Hasa Gun', 'Juliette Has A Gun'],
  ['Luxe Bottega Veneta', 'Bottega Veneta'],
  ['Luxe Carolina Herrera', 'Carolina Herrera'],
  ['Atelier Versace', 'Versace'],
  ['Lux Chanel', 'Chanel'],
  ['Luxe Dior', 'Dior'],
  ['Lux D&G', 'Dolce & Gabbana'],
  ['Lux Ajmal', 'Ajmal'],
  ['100 Bon', '100 Bon'],
  ['AJ Arabia', 'AJ Arabia'],
  ['Alfred Sung', 'Alfred Sung'],
  ['Angel Schlesser', 'Angel Schlesser'],
  ['Bois 1920', 'Bois 1920'],
  ['Bond No. 9', 'Bond No. 9'],
  ['Bond No9', 'Bond No. 9'],
  ['Christian Louboutin', 'Christian Louboutin'],
  ['Diana Vreeland', 'Diana Vreeland'],
  ['Franck Olivier', 'Franck Olivier'],
  ['House of Sillage', 'House of Sillage'],
  ['John Varvatos', 'John Varvatos'],
  ['Sarah Jessica Parker', 'Sarah Jessica Parker'],
  ['Teo Cabanel', 'Teo Cabanel'],
  ['Viktor Rolf', 'Viktor & Rolf'],
  ['L’Artisan', 'L’Artisan Parfumeur'],
  ["L'Artisan", 'L’Artisan Parfumeur'],
  ['Carolina Herrera', 'Carolina Herrera'],
  ['Herrera', 'Carolina Herrera'],
  ['Jean Paul Gaultier', 'Jean Paul Gaultier'],
  ['JPG', 'Jean Paul Gaultier'],
  ['Memo', 'Memo Paris'],
  ['Police', 'Police'],
  ['Dali', 'Salvador Dali'],
  ['12 Parfumeurs Français', '12 Parfumeurs Français'],
  ['12 Parfumeurs Francais', '12 Parfumeurs Français'],
  ['A. Banderas', 'Antonio Banderas'],
  ['Antonio Banderas', 'Antonio Banderas'],
  ['Abercrombie & Fitch', 'Abercrombie & Fitch'],
  ['Acqua di Parma', 'Acqua di Parma'],
  ['Aedes de Venustas', 'Aedes de Venustas'],
  ['Agent Provocateur', 'Agent Provocateur'],
  ['Alexander McQueen', 'Alexander McQueen'],
  ['Alfred Dunhill', 'Dunhill'],
  ['Alyson Oldoini', 'Alyson Oldoini'],
  ['Armand Basi', 'Armand Basi'],
  ['Atelier Cologne', 'Atelier Cologne'],
  ['Bottega Veneta', 'Bottega Veneta'],
  ['Brunello Cucinelli', 'Brunello Cucinelli'],
  ['Britney Spears', 'Britney Spears'],
  ['Calvin Klein', 'Calvin Klein'],
  ['CK', 'Calvin Klein'],
  ['Carolina Herrera', 'Carolina Herrera'],
  ['Christian Dior', 'Dior'],
  ['D&G', 'Dolce & Gabbana'],
  ['Dolce & Gabbana', 'Dolce & Gabbana'],
  ['Dolce Gabbana', 'Dolce & Gabbana'],
  ['D. Gabbana', 'Dolce & Gabbana'],
  ['Elizabeth Arden', 'Elizabeth Arden'],
  ['E.Arden', 'Elizabeth Arden'],
  ['Elie Saab', 'Elie Saab'],
  ['Estée Lauder', 'Estée Lauder'],
  ['Estee Lauder', 'Estée Lauder'],
  ['E.L', 'Estée Lauder'],
  ['Etat Libre d’Orange', "Etat Libre d'Orange"],
  ["Etat Libre d'Orange", "Etat Libre d'Orange"],
  ['Franck Boclet', 'Franck Boclet'],
  ['Geza Schoen', 'Escentric Molecules'],
  ['Gian Marco Venturi', 'Gian Marco Venturi'],
  ['Giorgio Armani', 'Giorgio Armani'],
  ['Armani', 'Giorgio Armani'],
  ['Hermès', 'Hermès'],
  ['Hermes', 'Hermès'],
  ['Hermessence', 'Hermès'],
  ['Hugo Boss', 'Hugo Boss'],
  ['Boss', 'Hugo Boss'],
  ['Issey Miyake', 'Issey Miyake'],
  ['Jean Patou', 'Jean Patou'],
  ['Jimmy Choo', 'Jimmy Choo'],
  ['John Galliano', 'John Galliano'],
  ['Juicy Couture', 'Juicy Couture'],
  ['Juliette Has A Gun', 'Juliette Has A Gun'],
  ['Karl Lagerfeld', 'Karl Lagerfeld'],
  ['Kenneth Cole', 'Kenneth Cole'],
  ['L’Artisan Parfumeur', 'L’Artisan Parfumeur'],
  ["L'Artisan Parfumeur", 'L’Artisan Parfumeur'],
  ['Maison Martin Margiela', 'Maison Margiela'],
  ['Maison Margiela', 'Maison Margiela'],
  ['Michael Kors', 'Michael Kors'],
  ['Narciso Rodriguez', 'Narciso Rodriguez'],
  ['Nina Ricci', 'Nina Ricci'],
  ['Ormonde Jayne', 'Ormonde Jayne'],
  ['Paco Rabanne', 'Rabanne'],
  ['Paloma Picasso', 'Paloma Picasso'],
  ['Ralph Lauren', 'Ralph Lauren'],
  ['Ramon Monegal', 'Ramon Monegal'],
  ['Roberto Cavalli', 'Roberto Cavalli'],
  ['Salvatore Ferragamo', 'Salvatore Ferragamo'],
  ['S.Ferragamo', 'Salvatore Ferragamo'],
  ['Salvador Dali', 'Salvador Dali'],
  ['Serge Lutens', 'Serge Lutens'],
  ['Thierry Mugler', 'Mugler'],
  ['Tommy Hilfiger', 'Tommy Hilfiger'],
  ['Van Cleef & Arpels', 'Van Cleef & Arpels'],
  ['Viktor & Rolf', 'Viktor & Rolf'],
  ['Yves Saint Laurent', 'Yves Saint Laurent'],
  ['YSL', 'Yves Saint Laurent'],
  ['Maison Francis Kurkdjian', 'Maison Francis Kurkdjian'],
  ['Jean Paul Gaultier', 'Jean Paul Gaultier'],
  ['Initio Parfums Privés', 'Initio Parfums Privés'],
  ['Initio Parfums Prives', 'Initio Parfums Privés'],
  ['Liquides Imaginaires', 'Liquides Imaginaires'],
  ['Marc-Antoine Barrois', 'Marc-Antoine Barrois'],
  ['Marc Antoine Barrois', 'Marc-Antoine Barrois'],
  ['Vilhelm Parfumerie', 'Vilhelm Parfumerie'],
  ['Lorenzo Pazzaglia', 'Lorenzo Pazzaglia'],
  ['Parfums de Marly', 'Parfums de Marly'],
  ['Frederic Malle', 'Frederic Malle'],
  ['Maison Crivelli', 'Maison Crivelli'],
  ['Clive Christian', 'Clive Christian'],
  ['Attar Collection', 'Attar Collection'],
  ['Tiziana Terenzi', 'Tiziana Terenzi'],
  ['Louis Vuitton', 'Louis Vuitton'],
  ['Penhaligon’s', 'Penhaligon’s'],
  ["Penhaligon's", 'Penhaligon’s'],
  ['Memo Paris', 'Memo Paris'],
  ['Tom Ford', 'Tom Ford'],
  ['Le Labo', 'Le Labo'],
  ['Ex Nihilo', 'Ex Nihilo'],
  ['Amouage', 'Amouage'],
  ['Aerin', 'Aerin'],
  ['Affinessence', 'Affinessence'],
  ['Ajmal', 'Ajmal'],
  ['Alaïa', 'Alaïa'],
  ['Alaia', 'Alaïa'],
  ['Armaf', 'Armaf'],
  ['Azzaro', 'Azzaro'],
  ['Balenciaga', 'Balenciaga'],
  ['Baldessarini', 'Baldessarini'],
  ['Bentley', 'Bentley'],
  ['Boucheron', 'Boucheron'],
  ['Brioni', 'Brioni'],
  ['Burberry', 'Burberry'],
  ['Byredo', 'Byredo'],
  ['Bvlgari', 'Bvlgari'],
  ['Cacharel', 'Cacharel'],
  ['Cartier', 'Cartier'],
  ['Celine', 'Celine'],
  ['Cerruti', 'Cerruti'],
  ['Chanel', 'Chanel'],
  ['Chloé', 'Chloé'],
  ['Chloe', 'Chloé'],
  ['Chopard', 'Chopard'],
  ['Clinique', 'Clinique'],
  ['Coach', 'Coach'],
  ['Creed', 'Creed'],
  ['Davidoff', 'Davidoff'],
  ['Diesel', 'Diesel'],
  ['Dior', 'Dior'],
  ['Diptyque', 'Diptyque'],
  ['DKNY', 'DKNY'],
  ['Dsquared2', 'Dsquared2'],
  ['Dunhill', 'Dunhill'],
  ['Eisenberg', 'Eisenberg'],
  ['Escada', 'Escada'],
  ['Etro', 'Etro'],
  ['Fendi', 'Fendi'],
  ['Floraïku', 'Floraïku'],
  ['Floraiku', 'Floraïku'],
  ['Givenchy', 'Givenchy'],
  ['Gucci', 'Gucci'],
  ['Guerlain', 'Guerlain'],
  ['Hermetica', 'Hermetica'],
  ['Jil Sander', 'Jil Sander'],
  ['Joop', 'Joop!'],
  ['Jovoy', 'Jovoy'],
  ['Kenzo', 'Kenzo'],
  ['Lacoste', 'Lacoste'],
  ['Lalique', 'Lalique'],
  ['Lancôme', 'Lancôme'],
  ['Lancome', 'Lancôme'],
  ['Lanvin', 'Lanvin'],
  ['Loewe', 'Loewe'],
  ['Lolita Lempicka', 'Lolita Lempicka'],
  ['M. Micallef', 'M. Micallef'],
  ['Micallef', 'M. Micallef'],
  ['MDCI', 'MDCI Parfums'],
  ['Miu Miu', 'Miu Miu'],
  ['Moschino', 'Moschino'],
  ['Mugler', 'Mugler'],
  ['Ormaie', 'Ormaie'],
  ['Ojar', 'Ojar'],
  ['Omanluxury', 'Omanluxury'],
  ['Prada', 'Prada'],
  ['Rabanne', 'Rabanne'],
  ['Rancé', 'Rancé 1795'],
  ['Rance', 'Rancé 1795'],
  ['Rochas', 'Rochas'],
  ['Shiseido', 'Shiseido'],
  ['Sisley', 'Sisley'],
  ['Trussardi', 'Trussardi'],
  ['HFC', 'HFC'],
  ['Kilian Paris', 'Kilian'],
  ['By Kilian', 'Kilian'],
  ['Kilian', 'Kilian'],
  ['Mancera', 'Mancera'],
  ['Montale', 'Montale'],
  ['Nishane', 'Nishane'],
  ['Sospiro', 'Sospiro'],
  ['Versace', 'Versace'],
  ['Xerjoff', 'Xerjoff'],
] satisfies ReadonlyArray<readonly [alias: string, canonical: string]>;

export const brandAliases = [...aliases].sort((a, b) => b[0].length - a[0].length);
